import { InvoiceData } from '@/types/invoice';

export const DEFAULT_SIGNATORY_NAMES = [
  'Md. Rakibul Islam',
  'Md. Habibur Rahman',
  'Iftekhar Alam Shuvo',
  'Dhruba Paul',
];

export const DEFAULT_SIGNATORY_TITLES = [
  'CEO',
  'COO',
  'CPO',
  'CFO',
];

export const CODEPHILIC_COMPANY_DEFAULT = {
  name: 'CodePhilic Limited',
  legalName: 'CodePhilic Limited',
  tagline: 'We Architect Imagination',
  regNo: 'RJSC Reg: C-213655/2026',
  vatNo: '',
  address: 'Arif Nagar, Santosh, Tangail.',
  cityCountry: 'Bangladesh',
  email: 'contact@codephilic.com',
  phone: '01812049163 / 0172889798',
  website: 'https://codephilic.com',
  logoUrl: '/cpLOGO.png',
};

export const DEFAULT_PAYMENT_DETAILS = {
  bankName: 'Standard Chartered Bank (International Corporate Banking)',
  accountName: 'CODEPHILIC PRIVATE LIMITED',
  accountNumber: '8492-3849-0192-44',
  routingNumber: '019482701',
  swiftBic: 'SCBLBDDX',
  iban: 'BD18SCBL000084923849019244',
  paymentMethod: 'International Wire Transfer / SWIFT / ACH / Stripe',
  paymentLink: 'https://pay.codephilic.com/invoices',
  upiOrId: 'wire-transfers@codephilic.com',
  cashReceiver: 'Authorized CodePhilic Representative',
  cashInstructions: 'Cash handed over in person upon milestone completion / delivery. Official money receipt issued.',
};

export const DEFAULT_INVOICE: InvoiceData = {
  id: 'cp-inv-initial',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  company: { ...CODEPHILIC_COMPANY_DEFAULT },
  client: {
    companyName: 'AeroCloud Systems Inc.',
    contactPerson: 'David K. Richardson',
    email: 'finance@aerocloud.io',
    phone: '+1 (415) 892-4410',
    address: '500 Howard Street, Suite 400',
    cityCountry: 'San Francisco, CA 94105, USA',
    taxId: 'US-EIN-94-3829102',
    poNumber: 'PO-2025-ACS-994',
  },
  items: [
    {
      id: 'item-1',
      title: 'Web Application Architecture & Frontend Engineering',
      description: 'Enterprise dashboard frontend engineering, component system, API integration, and role-based authentication.',
      quantity: 1,
      rate: 4500,
      taxable: true,
    },
    {
      id: 'item-2',
      title: 'Cloud Infrastructure Setup & CI/CD Deployment',
      description: 'Docker containerization, cloud environment setup, automated staging and production deployment pipelines.',
      quantity: 35,
      rate: 90,
      taxable: true,
    },
    {
      id: 'item-3',
      title: 'AI Workflow Integration & Vector Search',
      description: 'Custom retrieval pipeline, vector database indexing, prompt templates, and streaming API endpoints.',
      quantity: 1,
      rate: 3200,
      taxable: true,
    },
    {
      id: 'item-4',
      title: 'Production SLA Support & Maintenance (Quarterly)',
      description: 'System uptime monitoring, dependency updates, security auditing, and on-call engineering support.',
      quantity: 1,
      rate: 1200,
      taxable: false,
    },
  ],
  meta: {
    invoiceNumber: 'CP-INV-2025-0042',
    issueDate: new Date().toISOString().split('T')[0],
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    paymentTerms: 'Net 30 Days',
    currency: 'USD',
    currencySymbol: '$',
    status: 'PENDING',
    theme: 'signature',
    notes: 'Thank you for your business. Please reference invoice CP-INV-2025-0042 when remitting payment.',
    terms: '1. Payment is due within 30 days of the invoice date.\n2. Bank wire transfer fees must be absorbed by the remitter.\n3. Intellectual property rights for deliverables transfer to client upon receipt of full payment.',
    signatoryName: 'Md. Rakibul Islam',
    signatoryRole: 'CEO',
    showQrCode: true,
    paymentMethodType: 'bank',
    discountType: 'percentage',
    discountValue: 5,
    taxRate: 7.5,
    shippingFee: 0,
    amountPaid: 0,
  },
  payment: { ...DEFAULT_PAYMENT_DETAILS },
};

export interface InvoiceTemplatePreset {
  id: string;
  name: string;
  badge: string;
  client: InvoiceData['client'];
  items: InvoiceData['items'];
  meta: Partial<InvoiceData['meta']>;
}

export const INVOICE_PRESETS: InvoiceTemplatePreset[] = [
  {
    id: 'saas-cloud',
    name: 'Enterprise Cloud & SaaS Architecture',
    badge: 'Flagship Tech',
    client: {
      companyName: 'HyperScale AI Technologies Inc.',
      contactPerson: 'Elena Rostova',
      email: 'accounting@hyperscale.ai',
      phone: '+1 (650) 412-9021',
      address: '220 University Ave, Palo Alto',
      cityCountry: 'California 94301, USA',
      taxId: 'US-EIN-88-2910492',
      poNumber: 'PO-HS-8821',
    },
    items: [
      {
        id: 'p-1',
        title: 'Microservices Architecture & API Gateway Refactoring',
        description: 'Scalable distributed services on Node.js/Go, GraphQL federation, and Kafka event streaming.',
        quantity: 1,
        rate: 6500,
        taxable: true,
      },
      {
        id: 'p-2',
        title: 'Next.js 16 Web Application Frontend & Design System',
        description: 'Pixel-perfect responsive frontend, high-fidelity UI components, state management, and edge caching.',
        quantity: 60,
        rate: 90,
        taxable: true,
      },
      {
        id: 'p-3',
        title: 'Cloud Security Audit & Penetration Testing',
        description: 'OWASP top 10 vulnerability assessment, automated fuzzing, and security compliance certificate.',
        quantity: 1,
        rate: 2400,
        taxable: false,
      },
    ],
    meta: {
      currency: 'USD',
      currencySymbol: '$',
      paymentTerms: 'Net 30 Days',
      status: 'PENDING',
      discountType: 'percentage',
      discountValue: 5,
      taxRate: 8,
    },
  },
  {
    id: 'ai-consulting',
    name: 'Generative AI & LLM Systems',
    badge: 'AI & Data',
    client: {
      companyName: 'Cognitive Dynamics Ltd.',
      contactPerson: 'Marcus Vance',
      email: 'marcus@cognitivedynamics.co.uk',
      phone: '+44 20 7946 0912',
      address: '30 St Mary Axe, City of London',
      cityCountry: 'London EC3A 8EP, United Kingdom',
      taxId: 'GB-VAT-992-1082-11',
      poNumber: 'CD-LLM-2025-04',
    },
    items: [
      {
        id: 'p-4',
        title: 'Custom RAG Pipeline & Multi-Agent Workflow Engine',
        description: 'Retrieval Augmented Generation with hybrid search (dense + sparse), reranking, and multi-agent coordination.',
        quantity: 1,
        rate: 8500,
        taxable: true,
      },
      {
        id: 'p-5',
        title: 'Model Fine-Tuning & Quantization Pipeline',
        description: 'LoRA fine-tuning for domain-specific technical documentation extraction and vLLM deployment.',
        quantity: 1,
        rate: 4200,
        taxable: true,
      },
      {
        id: 'p-6',
        title: 'Vector Database Infrastructure & Monitoring',
        description: 'Qdrant cluster setup, Prometheus/Grafana latency telemetry, and semantic caching.',
        quantity: 1,
        rate: 1800,
        taxable: true,
      },
    ],
    meta: {
      currency: 'GBP',
      currencySymbol: '£',
      paymentTerms: 'Net 15 Days',
      status: 'PAID',
      discountType: 'fixed',
      discountValue: 500,
      taxRate: 5,
    },
  },
  {
    id: 'mobile-uiux',
    name: 'Mobile App & UI/UX Product Design',
    badge: 'Design & Mobile',
    client: {
      companyName: 'FinVortex Global Holdings',
      contactPerson: 'Sarah Lin',
      email: 'finance@finvortex.sg',
      phone: '+65 6789 0123',
      address: 'Marina Bay Financial Centre, Tower 2',
      cityCountry: 'Singapore 018983',
      taxId: 'SG-UEN-202391024K',
      poNumber: 'FV-PO-904',
    },
    items: [
      {
        id: 'p-7',
        title: 'Cross-Platform React Native iOS & Android App',
        description: 'Native bridging, biometrics auth, push notifications, offline syncing, and performance tuning.',
        quantity: 1,
        rate: 7200,
        taxable: true,
      },
      {
        id: 'p-8',
        title: 'High-Fidelity UI/UX Design System & Interactive Prototype',
        description: 'Comprehensive Figma token system, dark/light themes, typography scale, and 40+ user flow screens.',
        quantity: 1,
        rate: 3500,
        taxable: true,
      },
      {
        id: 'p-9',
        title: 'App Store & Google Play Store Submission Package',
        description: 'Compliance review, privacy policy alignment, asset rendering, and test flight deployment.',
        quantity: 1,
        rate: 900,
        taxable: false,
      },
    ],
    meta: {
      currency: 'USD',
      currencySymbol: '$',
      paymentTerms: 'Due upon Receipt',
      status: 'PENDING',
      discountType: 'percentage',
      discountValue: 0,
      taxRate: 0,
    },
  },
  {
    id: 'local-bangladesh',
    name: 'Domestic Tech Advisory & SRE Retainer',
    badge: 'Local (BDT)',
    client: {
      companyName: 'Dhaka Fintech Solutions Ltd.',
      contactPerson: 'Kazi Farhan',
      email: 'accounts@dhakafintech.com.bd',
      phone: '+880 1711-223344',
      address: 'Gulshan 2, Road 45, House 12',
      cityCountry: 'Dhaka 1212, Bangladesh',
      taxId: 'BIN: 002948192-0201',
      poNumber: 'DFS-2025-CONTRACT-02',
    },
    items: [
      {
        id: 'p-10',
        title: 'Core Banking Payment Gateway Integration & MFS API',
        description: 'Direct integration with bKash, Nagad, Visa, Mastercard with ISO 8583 switch and automated reconciliation.',
        quantity: 1,
        rate: 280000,
        taxable: true,
      },
      {
        id: 'p-11',
        title: 'DevOps & 99.99% High Availability Kubernetes Retainer (Q1)',
        description: 'Dedicated cloud architect support, failover setup, automated backups, and database replication.',
        quantity: 3,
        rate: 65000,
        taxable: true,
      },
    ],
    meta: {
      currency: 'BDT',
      currencySymbol: '৳',
      paymentTerms: 'Net 30 Days',
      status: 'PENDING',
      discountType: 'percentage',
      discountValue: 5,
      taxRate: 5,
    },
  },
];
